### ISSUE TITLE
Member Profile Page

### ISSUE THREAD

**Issue by moseley** [ComTacTraining/ctt#19]
The member profile page should allow a member to set their custom alarm names and default tips display option.

**Comment by softwarebusiness588** [comment]
Do you have some additional details regarding the custom alarms and default tips display option? A high-level overview or example would be helpful.

**Comment by moseley** [comment]
Members gain the ability to specify custom settings:
Alarms: The names of the units (Defaults to: Engine 1, Engine 2, Engine 3, Truck 1, Truck 2, Battalion 1) can be customized. There are 3  different alarms that can be set. 
Dispatch center: can also be custom named.
Tips Display: This allows the tips that are shown in bottom right corner in the demo to be shown of not. If they are hiddn it is an additional level of difficult/challenge for the member.

**Comment by softwarebusiness588** [comment]
Thanks for clarifying! What will the event triggers be for Alarm 2 and Alarm 3. Alarm 1 is set to start at the beginning of the video. What will be the triggers for 2 and 3?

**Comment by moseley** [comment]
If a command contains a request for a second or third alarm, the dispatcher will confirm the request and then after a waiting period the dispatcher will announce the second or third alarm units that are arriving.

**Comment by moseley** [comment]
The alarms should allow for any number of units to be added. Alarms should be thought of as a list of custom names. Alarm 1 must account for a few additional settings: it must specify which unit is the first on scene (the unit of the person speaking) and which unit is the incoming command officer. Also it must have a minimum of 3 more units as it requires 3 unit assignments to advance in the demo. A member should be able to add as many more units as they want (maybe max 10).

The 2nd & 3rd alarms only require a minimum of 1 unit, but it would typically be a similar number to alarm 1. They are each just a list of custom names.

Perhaps the UI could be a form that contains a text field that would add a [chip](https://material-ui.com/components/chips/). The form for alarm 1 would also have checkboxes for first on scene or incoming command officer. Those unit roles could perhaps be different colored chips.
