### ISSUE TITLE
Member Education Section

### ISSUE THREAD

**Issue by moseley** [ComTacTraining/ctt#23]
Ensure the Education scrolling text is displayed after the face-to-face is completed for members.

**Comment by softwarebusiness588** [comment]
Is the "education scrolling text" the text that displays at the beginning of each video? How can we tell if the face-to-face is completed for members?
![image0](https://user-images.githubusercontent.com/71161568/118747678-75d49200-b828-11eb-9e0a-f77d4df348c4.png)

**Comment by moseley** [comment]
The education scrolling text is displayed in the same way as the initial alarm, but it is displayed at the end after the face-to-face is completed. This is only for the member evolutions, not the demo.

**Comment by moseley** [comment]
Regarding the face-to-face, it occurs after the "Incident Within an Incident" by the `IncomingCommandOfficer`. The face-to-face is marked as completed following the command after the face-to-face request.

**Comment by moseley** [comment]
The Education section is displayed after a face-to-face.
