### ISSUE TITLE
Member Evaluation

### ISSUE THREAD

**Issue by moseley** [ComTacTraining/ctt#24]
Ensure that the Evaluation form is displayed after the Education scrolling text for members. An API update will be required to store the member + evolution result.

**Comment by softwarebusiness588** [comment]
Can you point out the "Education Scrolling Text" on the member's tab? Also, I couldn't find the evaluation form. Do we need to build it from scratch?

**Comment by moseley** [comment]
The evaluation form has been built but it does not yet save the submission. This is thee directory where thee evaluation code lives: [https://github.com/ComTacTraining/ctt/tree/main/components/Evolution/Evaluation](https://github.com/ComTacTraining/ctt/tree/main/components/Evolution/Evaluation)
