### ISSUE TITLE
Assignments

### ISSUE THREAD

**Issue by ComTacTraining** [ComTacTraining/ctt#7]
Not all assignments are repeated back verbally

**Comment by moseley** [comment]
Can you please copy and paste the command used to request the assignment?

**Comment by moseley** [comment]
I'm going to close this issue for now as the units are able to be assigned via the keyboard command. Issue #48 has been added for issues related to the speech-to-text "Engine to" rather than "Engine 2". Please reopen or create a new issue if this issue is still happening.
