### ISSUE TITLE
group names

### ISSUE THREAD

**Issue by ComTacTraining** [ComTacTraining/CTT#8]
Jerm
The first assigned unit becomes fire attack is there an option for the group name to be hippopotumas group as we previously discussed?  Tried to use interior and did not give it to me.

**Comment by moseley** [comment]
The group assignments current work by matching the "terms". For fire attack, the terms are: attack, attach, rescue, and interior. If a unit name is mentioned (i.e. Engine 2) and also one of the terms (i.e. interior) that will result in an assignment. Future requests from this unit can be made to Engine 2 or Fire Attack, but not a custom assigned name.

**Comment by moseley** [comment]
Issue #12 has been added as an enhancement.
